name: Daemon CI

on:
  pull_request:
    paths: 
      - 'daemon/**'

jobs:
  daemon:
    name: Daemon - Format Check and Build 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Clang format check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '20'
          check-path: daemon

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libnl-genl-3-dev \
            libevent-dev \
            make

      - name: Build and install ION
        run: |
          wget -q https://github.com/nasa-jpl/ION-DTN/archive/refs/tags/ion-open-source-4.1.3.tar.gz
          tar -zxf ion-open-source-4.1.3.tar.gz
          cd ION-DTN-ion-open-source-4.1.3
          make
          sudo make install

      - name: Build daemon
        working-directory: daemon
        run: |
          make clean || true
          make
