name: Kernel Module CI

on:
  pull_request:
    # paths: 
    #   - 'bp_socket/**'

jobs:
  kernel-module:
    name: bp_socket - Format Check, Build, Sparse Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            linux-headers-$(uname -r) \
            sparse \
            make

      - name: Clang format check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '20'
          check-path: bp_socket

      - name: Build kernel module
        working-directory: bp_socket
        run: |
          make clean || true
          make 

      - name: Sparse static analysis
        working-directory: bp_socket
        run: |
          make clean || true
          make sparse
